### PR TITLE
Respect CSS cascade when determining `anchor-name`

### LINKED ISSUE #218: [BUG] `anchor-name` doesn't respect CSS cascade
**Describe the bug**
The `anchor-name` property doesn't respect the CSS cascade. For example:

```html
.anchor {
  anchor-name: --name;
}
.anchor {
  anchor-name: --other-name;
}
.positioned {
  position: absolute;
  top: anchor(--name, bottom); // this should not anchor to `.anchor`, but currently does.
}
```

**To Reproduce**
I created a test demonstrating the issue here: https://github.com/oddbird/css-anchor-positioning/compare/main...mmalerba:css-anchor-positioning:cascade

**Expected behavior**
The `anchor` function should only match the `anchor-name` that is actually applied by the cascade

**Additional context**
This can be solved by shifting `anchor-name` into a custom property, but the custom property inherits by default, so we would either have to disable that with `@property` (potentially unacceptable due to browser support?) or just be careful to verify we're not reading inherited values. This is how I handled a similar issue for `anchor-scope`: [`32f04d8` (#217)](https://github.com/oddbird/css-anchor-positioning/pull/217/commits/32f04d88e745829ba0b2fcd42f98612ad5c9fdea)

### PR DESCRIPTION
**Pull request by mmalerba**
Fixes #218, #212

### CODE REVIEW

File: src/dom.ts [hunk 1]
```diff
@@ -0,0 +1,238 @@
+import { type VirtualElement } from '@floating-ui/dom';
+import { nanoid } from 'nanoid/non-secure';
+import { SHIFTED_PROPERTIES } from './cascade.js';
```
Comment (jgerigmeyer) [inline src/dom.ts:3]:
```suggestion
import { nanoid } from 'nanoid/non-secure';

import { SHIFTED_PROPERTIES } from './cascade.js';
```

File: tests/helpers.ts [hunk 2]
```diff
@@ -1,13 +1,26 @@
 import fs from 'fs';
 import path from 'path';
 import { fileURLToPath } from 'url';
+import { cascadeCSS } from '../src/cascade.js';
+import { StyleData } from '../src/utils.js';
```
Comment (jgerigmeyer) [inline tests/helpers.ts:5]:
```suggestion

import { cascadeCSS } from '../src/cascade.js';
import { type StyleData } from '../src/utils.js';
```

File: src/dom.ts [hunk 3]
```diff
@@ -0,0 +1,238 @@
...
+ */
+export const enum AnchorScopeValue {
+  All = 'all',
+  None = 'none',
+}
+
+/**
+ * Gets the computed value of a CSS property for an element or pseudo-element.
+ *
+ * Note: values for properties that are not natively supported are *awlways* subject to CSS
```
Comment (jgerigmeyer) [inline src/dom.ts:34]:
```suggestion
 * Note: values for properties that are not natively supported are *always* subject to CSS
```

File: src/dom.ts [hunk 4]
```diff
@@ -0,0 +1,238 @@
...
+ * Used instead of an HTMLElement as a handle for pseudo-elements.
+ */
+export interface PseudoElement extends VirtualElement {
+  fakePseudoElement: HTMLElement;
+  computedStyle: CSSStyleDeclaration;
+  removeFakePseudoElement(): void;
+}
+
+/**
+ * Possible values for `anchor-scope` (in addition any valid dashed identifier)
```
Comment (jgerigmeyer) [inline src/dom.ts:24]:
```suggestion
 * Possible values for `anchor-scope` (in addition to any valid dashed identifier)
```

File: src/dom.ts [hunk 5]
```diff
@@ -0,0 +1,238 @@
...
+  prop = SHIFTED_PROPERTIES[prop] ?? prop;
+  const computedStyle =
+    el instanceof HTMLElement ? getComputedStyle(el) : el.computedStyle;
+  return computedStyle.getPropertyValue(prop).trim();
+}
+
+/**
+ * Checks whether a given element or pseudo-element has the given property value.
+ *
+ * Note: values for properties that are not natively supported are *awlways* subject to CSS
```
Comment (jgerigmeyer) [inline src/dom.ts:50]:
```suggestion
 * Note: values for properties that are not natively supported are *always* subject to CSS
```

File: src/dom.ts [hunk 6]
```diff
@@ -0,0 +1,238 @@
...
+  document.head.append(sheet);
+
+  const insertionPoint =
+    pseudoElementPart === '::before' ? 'afterbegin' : 'beforeend';
+  element.insertAdjacentElement(insertionPoint, fakePseudoElement);
+  return { fakePseudoElement, sheet, computedStyle };
+}
+
+/**
+ * Finds the first scollable parent of the given element
```
Comment (jgerigmeyer) [inline src/dom.ts:98]:
```suggestion
 * Finds the first scrollable parent of the given element
```

File: src/dom.ts [hunk 7]
```diff
@@ -0,0 +1,238 @@
...
+
+    currentElement = currentElement.parentElement;
+  }
+
+  return currentElement;
+}
+
+/**
+ * Gets the scroll position of the first scrollable parent
+ * (or the scoll position of the element itself, if it is scrollable).
```
Comment (jgerigmeyer) [inline src/dom.ts:117]:
```suggestion
 * (or the scroll position of the element itself, if it is scrollable).
```

File: src/dom.ts [hunk 8]
```diff
@@ -0,0 +1,238 @@
...
+
+      removeFakePseudoElement() {
+        fakePseudoElement.remove();
+        sheet.remove();
+      },
+
+      // For https://floating-ui.com/docs/autoupdate#ancestorscroll to work on `VirtualElement`s.
+      contextElement: element,
+
+      // https://floating-ui.com/docs/virtual-elements.
```
Comment (jgerigmeyer) [inline src/dom.ts:177]:
```suggestion
      // https://floating-ui.com/docs/virtual-elements
```

**Review by jgerigmeyer — CHANGES_REQUESTED** [review]
This is great, and goes a long way toward #216 as well. A few typos and minor comments, but nothing concerning functionality. 👏

**Review by jgerigmeyer — APPROVED** [review]
